// Generated by CodiumAI
import React from 'react';
import RouteLinks from './RouteLinks';
import { shallow, configure } from 'enzyme';
import Adapter from '@wojtekmaj/enzyme-adapter-react-17';

configure({ adapter: new Adapter() });

describe('RouteLinks', () => {

  // Renders a Link component when the 'to' prop is an internal link.
  it('should render a Link component when the \'to\' prop is an internal link', () => {
    const wrapper = shallow(<RouteLinks to="/internal" />);
    expect(wrapper.find(Link)).toHaveLength(1);
  });

  // Throws an error when the 'to' prop is not a string.
  it('should throw an error when the \'to\' prop is not a string', () => {
    expect(() => {
      shallow(<RouteLinks to={123} />);
    }).toThrow();
  });
});
